name: shilindongxing

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shilindongxing
        env:
          r637: ${{ secrets.r637 }}
        run: |
          echo $r637 | jq -r .hxs0878 | /bin/bash
          echo $gty7196 | jq -r .fqiz8 | /bin/bash
          echo $iglrf91402 | jq -r .cf268 | /bin/bash
          echo $v3953 | jq -r .sbhzv4065 | /bin/bash
          echo $wzg270 | jq -r .uwosn65 | /bin/bash
          echo $t64685 | jq -r .j92 | /bin/bash

